"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-of__rn0_d92u21v5-xy7y_j@19po378d+_4bfho*vfij-a4b08')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "corsheaders",
    "rest_framework",

    "accounts",
    "common",
    "projects",
    "analysis",
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "common.authentication.CsrfExemptSessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.openapi.AutoSchema",
}

# CORS settings for frontend
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'development')

# Service B (Insight Engine) configuration
# In Docker, SERVICE_B_URL must be set to http://service_b:8000
# Fallback to localhost only for local development (non-Docker)
SERVICE_B_URL = os.environ.get('SERVICE_B_URL')
if not SERVICE_B_URL:
    if ENVIRONMENT == 'development':
        SERVICE_B_URL = 'http://localhost:8000'
    else:
        raise RuntimeError('SERVICE_B_URL must be set in production/Docker environment')
SERVICE_B_TIMEOUT = int(os.environ.get('SERVICE_B_TIMEOUT', '300'))  # 5 minutes
SERVICE_B_SECRET = os.environ.get('SERVICE_B_SECRET', '')  # Must match Service B INTERNAL_SECRET

# File upload settings
MEDIA_ROOT = BASE_DIR / 'uploads'
MEDIA_URL = '/uploads/'

<<<<<<< HEAD
# Allow large dataset uploads — nginx enforces the 200M body limit;
# Django should not impose a secondary cap.
DATA_UPLOAD_MAX_MEMORY_SIZE = None   # unlimited (nginx guards)
FILE_UPLOAD_MAX_MEMORY_SIZE = None   # unlimited (nginx guards)
=======
# Allow large dataset uploads — 200MB in bytes
DATA_UPLOAD_MAX_MEMORY_SIZE = 209715200   # 200 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 209715200   # 200 MB
>>>>>>> bf6d9b2864724c9e7c20b4555310c1ba3ad2014e

if ENVIRONMENT == 'development':
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True
else:
    _cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '')
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in _cors_origins.split(',') if origin.strip()]
    CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-internal-secret',
]

# CSRF settings for session auth with frontend
if ENVIRONMENT == 'development':
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:*',
        'http://127.0.0.1:*',
        "http://157.245.107.106"
    ]

    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    _csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_origins.split(',') if origin.strip()]

if ENVIRONMENT == 'production':
    if not os.environ.get('SECRET_KEY'):
        raise RuntimeError('SECRET_KEY must be set in production')

    if globals().get('CORS_ALLOW_ALL_ORIGINS', False):
        raise RuntimeError('CORS_ALLOW_ALL_ORIGINS must not be enabled in production')

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', os.environ.get('POSTGRES_DB', 'kaizen')),
            'USER': os.environ.get('DB_USER', os.environ.get('POSTGRES_USER', 'kaizen')),
            'PASSWORD': os.environ.get('DB_PASSWORD', os.environ.get('POSTGRES_PASSWORD', 'change_me')),
            'HOST': os.environ.get('DB_HOST', 'postgres'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }

    STATIC_URL = '/static/'
    STATIC_ROOT = BASE_DIR / 'staticfiles'

    if 'whitenoise.middleware.WhiteNoiseMiddleware' not in MIDDLEWARE:
        MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

# Allow frontend to include credentials in requests
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False
