upstream django {
    server service_a:8002;
}
server {
    listen 80;
    server_name app.kaizenx.in;

    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name app.kaizenx.in;

    ssl_certificate /etc/letsencrypt/live/app.kaizenx.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.kaizenx.in/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://django;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
