# Generated by Django 6.0.2 on 2026-09-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='firm_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
