name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 157.245.107.106
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/Kaizen_V1

            echo "📥 Pulling latest code..."
            git pull origin main

            echo "🛑 Stopping containers..."
            docker-compose down

            echo "🚀 Starting containers..."
            docker-compose up -d --build

            echo "✅ Deployment done"
